/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_protech_mix_SmartCalc_addThis
#define _Included_com_protech_mix_SmartCalc_addThis
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_protech_mix_SmartCalc_addThis
        (JNIEnv *env, jobject instance, jint x, jint y);

#ifdef __cplusplus
}
#endif
#endif
